CREATE TABLE PRICES (
    BRAND_ID   INTEGER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE NUMERIC(20, 2) NOT NULL, 
    CURR VARCHAR(5) NOT NULL,
    PRIMARY KEY (PRODUCT_ID, PRICE_LIST)
);